name: Build Project

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: npm install and build
        run: |
          npm install
          npm run build --if-present
      - name: Archive production artifacts
        uses: actions/upload-artifact@v3
        with:
          name: AnkiBotExtension
          path: dist

  publish:
    name: "Publish to GitHub Packages"
    needs: [build]
    runs-on: ubuntu-latest
    steps:
    - name: Upload
      uses: actions/download-artifact@v3
      with:
          name: AnkiBotExtension
    - uses: actions/setup-node@v3
      with:
        node-version: '16.x'
        registry-url: 'https://registry.npmjs.org'
    - run: npm publish dist
      env:
        NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}